config/routes.rb
Rails.application.routes.draw do

  devise_for :admin, skip: [:registrations, :passwords], controllers: {
    sessions: "admin/sessions"
  }

  devise_for :customers,skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }

  # Public側の記述
  root 'public/homes#top'
  get 'about', to: 'public/homes#about'
  scope module: :public do
    resources :cart_items, only: [:index, :update, :destroy, :create] do
      delete 'clear', on: :collection
    end
    resources :addresses, only: [:index, :edit, :create, :update, :destroy]
    post '/orders/confirm' => 'orders#confirm', as: "confirm_orders"
    get '/orders/confirm' => 'orders#confirm'
    resources :orders, only: [:new, :create, :index, :show] do
      collection do
        get 'complete'
      end
    end

    get '/customers/my_page' => 'customers#show'
    get '/customers/information/edit' => 'customers#edit'
    patch '/customers/information' => 'customers#update'
    get '/customers/check' => 'customers#check'
    get '/customers/out' => 'customers#out'

    resources :items, only: [:index, :show]
  end

  # Admin側の記述
  get 'admin', to: 'admin/homes#top'
  namespace :admin do
    resources :order_details, only: [:update]
    resources :orders, only: [:show, :update]
    resources :customers, only: [:index, :show, :edit, :update]
    resources :genres, only: [:index, :create, :edit, :update]
    resources :items, only: [:index, :new, :create, :show, :edit, :update]
  end

end

app/models/item.rb
class Item < ApplicationRecord
  has_one_attached :item_image
  has_many :cart_items, dependent: :destroy
  has_many :order_details, dependent: :destroy
  belongs_to :genre
  has_many :orders, through: :order_details

  validates :name, presence: true
  validates :introduction, presence: true
  validates :price, presence: true, numericality: { only_integer: true, greater_than: 0}


  def get_item_image(width, height)
    unless item_image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      item_image.attach(io: File.open(file_path), filename: 'no_image.jpg', content_type: 'image/jpeg')
    end
    item_image.variant(resize_to_fill: [width, height]).processed
  end
end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController
  before_action :authenticate_admin!

  def index
    @items = Item.page(params[:page]).per(10)
  end

  def new
    @item = Item.new
  end

  def create
    @item = Item.new(item_params)
    if @item.save
      flash[:notice] = "新しい商品を登録しました"
      redirect_to admin_item_path(@item.id)
    else
      @item = Item.new
      flash[:notice] = "商品の登録ができませんでした"
      render :new
    end
  end

  def show
    @item = Item.find(params[:id])
    @genre = Genre.find(@item.genre_id)
    @tax_rate = 0.08
    @tax_included_price = (@item.price * (1 + @tax_rate)).round
  end

  def edit
    @item = Item.find(params[:id])
  end

  def update
    item = Item.find(params[:id])
    if item.update(item_params)
      flash[:notice] = "商品情報が更新されました"
      redirect_to admin_item_path(item.id)
    else
      @item = Item.find(params[:id])
      flash[:notice] = "商品の更新ができませんでした"
      render :edit
    end
  end

  private
    def item_params
        params.require(:item).permit(:genre_id, :name, :introduction, :price, :item_image, :is_active)
    end

end

app/views/admin/items/create.html.erb
<h1>Admin::Itemes#create</h1>
<p>Find me in app/views/admin/itemes/create.html.erb</p>

app/views/admin/items/edit.html.erb
<div class='container'>
  <div class='row my-4'>
    <div class="col-md-8 mx-auto">
      <h4 class="d-inline bg-secondary text-white">　商品編集　</h4>
    </div>
  </div>
  <div class='row my-4'>
    <div class="col-md-6 mx-auto">
      <%= form_with model: @item, url: admin_item_path(@item), local: true do |f| %>
        <table>
          <tbody>
            <tr>
              <td style="padding-right: 20px;">
                <label>商品画像</label>
              </td>
              <td class="d-flex">
                <%= f.file_field :item_image, accept: "image/*" %>
              </td>
            </tr>
            <tr>
              <td style="padding-right: 20px;">
                <label>商品名</label>
              </td>
              <td class="d-flex">
                <%= f.text_field :name, style: "width: 100%;" %>
              </td>
            </tr>
            <tr>
              <td style="padding-right: 20px;">
                <label>商品説明</label>
              </td>
              <td class="d-flex">
                <%= f.text_area :introduction, rows: 5, style: "width: 100%;" %>
              </td>
            </tr>
            <tr>
              <td style="padding-right: 20px;">
                <label>ジャンル</label>
              </td>
              <td class="d-flex">
                <%= f.collection_select :genre_id, Genre.all ,:id, :name %>
              </td>
            </tr>
            <tr>
              <td style="padding-right: 20px;">
                <label>税抜価格</label>
              </td>
              <td class="d-flex">
                <%= f.text_field :price, style: "width: 90%;" %>円
              </td>
            </tr>
            <tr>
              <td style="padding-right: 20px;">
                <label>販売ステータス</label>
              </td>
              <td>
                <%= f.radio_button :is_active, true, id: "active" %>
                <%= f.label :is_active, "販売中", value: true, for: "active" %>
                <%= f.radio_button :is_active, false, id: "inactive" %>
                <%= f.label :is_active, "販売停止中", value: false, for: "inactive" %>
              </td>
            </tr>
            <tr>
              <td><%= f.submit '変更を保存', class: "btn btn-success", style: "font-weight: bold;" %></td>
            </tr>
          </tbody>
        </table>
      <% end %>
    </div>
  </div>
</div>

app/views/admin/items/index.html.erb
<div class='container'>
  <div class='row justify-content-md-center align-items-center my-4'>
    <div class="col-md-5 text-center">
      <h4 class="d-inline bg-secondary text-start text-white">　商品一覧　</h4>
    </div>
    <div class="col-md-4 text-right">
      <h1><%= link_to "+", new_admin_item_path, class: "btn btn-light rounded-circle border" %></h1>
    </div>
  </div>
  <div class='row my-4'>
    <div class="col-md-9 mx-auto">
      <div class='table-responsive'>
        <table class='table table-hover'>
          <thead class="thead-light font-weight-bold">
            <tr>
              <th>商品ID</th>
              <th>商品名</th>
              <th>税抜価格</th>
              <th>ジャンル</th>
              <th>ステータス</th>
            </tr>
          </thead>
          <tbody>
            <% @items.each do |item| %>
              <tr>
                <td>
                  <%= item.id %>
                </td>
                <td>
                  <%= link_to admin_item_path(item.id), style: "color: black; text-decoration: underline;" do %>
                    <%= item.name %>
                  <% end %>
                  </td>
                <td><%= number_with_delimiter(item.price, delimiter: ",") %></td>
                <td>
                  <% genre = Genre.find(item.genre_id) %>
                  <%= genre.name %>
                </td>
                <td class="font-weight-bold">
                  <% if item.is_active == true %>
                   <p class="text-success">販売中</p>
                  <% else %>
                    <p class="text-secondary">販売停止中</p>
                  <% end %>
                </td>
              </tr>
            <% end %>
          </tbody>
        </table>
      </div>
    </div>
  </div>
  <div class='row'>
    <div class="col">
      <div style="display: flex; justify-content: center;">
        <%= paginate @items, class: "pagination" %>
      </div>
    </div>
  </div>
</div>

app/views/admin/items/new.html.erb
<div class='container'>
  <div class='row my-4'>
    <div class="col-md-8 mx-auto">
      <h4 class="d-inline bg-secondary text-white">　商品新規登録　</h4>
    </div>
  </div>
  <div class='row my-4'>
    <div class="col-md-6 mx-auto">
      <%= form_with model: @item, url: admin_items_path, local: true do |f| %>
        <table>
          <tbody>
            <tr>
              <td style="padding-right: 20px;">
                <label>商品画像</label>
              </td>
              <td class="d-flex">
                <%= f.file_field :item_image, accept: "image/jpg" %>
              </td>
            </tr>
            <tr>
              <td style="padding-right: 20px;">
                <label>商品名</label>
              </td>
              <td class="d-flex">
                <%= f.text_field :name, placeholder:"商品名", style: "width: 100%;" %>
              </td>
            </tr>
            <tr>
              <td style="padding-right: 20px;">
                <label>商品説明</label>
              </td>
              <td class="d-flex">
                <%= f.text_area :introduction, placeholder:"ここに説明文を記述します", rows: 5, style: "width: 100%;" %>
              </td>
            </tr>
            <tr>
              <td style="padding-right: 20px;">
                <label>ジャンル</label>
              </td>
              <td class="d-flex">
                <%= f.collection_select :genre_id, Genre.all ,:id, :name, include_blank: "--選択してください--" %>
              </td>
            </tr>
            <tr>
              <td style="padding-right: 20px;">
                <label>税抜価格</label>
              </td>
              <td class="d-flex">
                <%= f.text_field :price, placeholder:"1000", style: "width: 90%;" %>円
              </td>
            </tr>
            <tr>
              <td style="padding-right: 20px;">
                <label>販売ステータス</label>
              </td>
              <td>
                <%= f.radio_button :is_active, true, id: "active" %>
                <%= f.label :is_active, "販売中", value: true, for: "active" %>
                <%= f.radio_button :is_active, false, id: "inactive" %>
                <%= f.label :is_active, "販売停止中", value: false, for: "inactive" %>
              </td>
            </tr>
            <tr>
              <td><%= f.submit '新規登録', class: "btn btn-success", style: "font-weight: bold;" %></td>
            </tr>
          </tbody>
        </table>
      <% end %>
    </div>
  </div>
</div>

app/views/admin/items/show.html.erb
<div class='container'>
  <div class='row my-4'>
    <div class="col-md-8 mx-auto">
      <h4 class="d-inline bg-secondary text-white">　商品詳細　</h4>
    </div>
  </div>
  <div class='row my-4'>
    <div class="col-md-4 d-flex justify-content-center align-items-center">
      <%= image_tag @item.get_item_image(200,200) %>
    </div>
    <div class="col-md-8">
      <table>
        <tbody>
          <tr>
            <td>商品名</td>
            <td style="padding-left: 40px;">
              <%= @item.name %>
            </td>
          </tr>
          <tr>
            <td>商品説明</td>
            <td style="padding-left: 40px;">
              <%= @item.introduction %>
            </td>
          </tr>
          <tr>
            <td>ジャンル</td>
            <td style="padding-left: 40px;">
              <%= @genre.name %>
            </td>
          </tr>
          <tr>
            <td>
              税込価格<br />
              (税抜価格)
            </td>
            <td style="padding-left: 40px;">
              <%= number_with_delimiter(@tax_included_price.round, delimiter: ",") %>（<%= number_with_delimiter(@item.price, delimiter: ",") %>）円
            </td>
          </tr>
          <tr>
            <td>販売ステータス</td>
            <td class="font-weight-bold", style="padding-left: 40px;">
              <% if @item.is_active == true %>
                <div class="text-success">販売中</div>
              <% else %>
                <div class="text-secondary">販売停止中</div>
              <% end %>
            </td>
          </tr>
          <tr>
            <td><%= link_to "編集する", edit_admin_item_path(@item), class: "btn btn-success", style: "font-weight: bold;" %></td>
          </tr>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/admin/items/update.html.erb
<h1>Admin::Itemes#update</h1>
<p>Find me in app/views/admin/itemes/update.html.erb</p>