config/routes.rb
Rails.application.routes.draw do

  devise_for :admin, skip: [:registrations, :passwords], controllers: {
    sessions: "admin/sessions"
  }

  devise_for :customers,skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }

  # Public側の記述
  root 'public/homes#top'
  get 'about', to: 'public/homes#about'
  scope module: :public do
    resources :cart_items, only: [:index, :update, :destroy, :create] do
      delete 'clear', on: :collection
    end
    resources :addresses, only: [:index, :edit, :create, :update, :destroy]
    post '/orders/confirm' => 'orders#confirm', as: "confirm_orders"
    get '/orders/confirm' => 'orders#confirm'
    resources :orders, only: [:new, :create, :index, :show] do
      collection do
        get 'complete'
      end
    end

    get '/customers/my_page' => 'customers#show'
    get '/customers/information/edit' => 'customers#edit'
    patch '/customers/information' => 'customers#update'
    get '/customers/check' => 'customers#check'
    get '/customers/out' => 'customers#out'

    resources :items, only: [:index, :show]
  end

  # Admin側の記述
  get 'admin', to: 'admin/homes#top'
  namespace :admin do
    resources :order_details, only: [:update]
    resources :orders, only: [:show, :update]
    resources :customers, only: [:index, :show, :edit, :update]
    resources :genres, only: [:index, :create, :edit, :update]
    resources :items, only: [:index, :new, :create, :show, :edit, :update]
  end

end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :shipping_addresses, dependent: :destroy
  has_many :orders, dependent: :destroy
  has_many :cart_items, dependent: :destroy

  validates :last_name, presence: true
  validates :first_name, presence: true
  validates :last_name_kana, presence: true
  validates :first_name_kana, presence: true
  validates :postal_code, presence: true
  validates :address, presence: true
  validates :telephone_number, presence: true

  def active_for_authentication?
    super && (self.is_active == true)
  end

end

app/controllers/admin/customers_controller.rb
class Admin::CustomersController < ApplicationController
  before_action :authenticate_admin!

  def index
    @customers = Customer.all.page(params[:page]).per(10) #ページネーション
  end

  def show
    @customer = Customer.find(params[:id])
  end

  def edit
    @customer = Customer.find(params[:id])
  end

  def update
    @customer = Customer.find(params[:id])
    if @customer.update(customer_params)
      puts @customer.errors.full_messages
      redirect_to admin_customer_path(@customer.id)
    else
      render :edit
    end
  end

  private

  def customer_params
    params.require(:customer).permit(:last_name, :first_name, :last_name_kana, :first_name_kana,
                        :postal_code, :address, :telephone_number, :email, :is_active)
  end
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/views/admin/customers/edit.html.erb
<!--顧客編集画面　10P-->
<div class="container">
  <div class="row my-3">
    <div>
      <h3><%= @customer.last_name + @customer.first_name %>さんの会員詳細</h3>
    </div>
    <%= form_with model: @customer, url: admin_customer_path(@customer), method: :patch do |f| %>
      <table class="table table-borderless form-group">
        <tr>
          <td>会員ID</td>
          <td><%= @customer.id %></td>
          <td></td>
        </tr>
        <tr>
          <td>氏名</td>
          <td><%= f.text_field :last_name, class: 'form-control', autofocus: true %></td>
          <td><%= f.text_field :first_name, class: 'form-control' %></td>
        </tr>
        <tr>
          <td>フリガナ</td>
          <td><%= f.text_field :last_name_kana, class: 'form-control' %></td>
          <td><%= f.text_field :first_name_kana, class: 'form-control' %></td>
        </tr>
        <tr>
          <td>郵便番号</td>
          <td><%= f.text_field :postal_code, class: 'form-control' %></td>
          <td></td>
        </tr>
        <tr>
          <td>住所</td>
          <td colspan="2"><%= f.text_field :address, class: 'form-control' %></td>
        </tr>
        <tr>
          <td>電話番号</td>
          <td><%= f.text_field :telephone_number, class: 'form-control' %></td>
          <td></td>
        </tr>
        <tr>
          <td>メールアドレス</td>
          <td><%= f.text_field :email, class: 'form-control' %></td>
          <td></td>
        </tr>
        <tr>
          <td>会員ステータス</td>
          <td>
            <%= f.radio_button :is_active, true, checked: @customer.is_active == true %>
            <%= f.label :is_active, '有効' %>
            <%= f.radio_button :is_active, false, checked: @customer.is_active == false %>
            <%= f.label :is_active, '退会' %>
          </td>
        </tr>
      </table>
      <div class="row mb-2">
        <%= f.submit "変更を保存", class: "btn btn-sm btn-success" %>
      </div>
    <% end %>
  </div>
</div>

app/views/admin/customers/index.html.erb
<div class='container'>
  <div class='row justify-content-md-center align-items-center my-4'>
    <div class="col-md-5 text-center">
      <h4 class="d-inline bg-secondary text-start text-white">　会員一覧　</h4>
    </div>
  </div>
  <div class='row my-4'>
    <div class="col-md-9 mx-auto">
      <div class='table-responsive'>
        <table class='table table-hover'>
          <thead class="thead-light font-weight-bold">
            <tr>
              <th>会員ID</th>
              <th>氏名</th>
              <th>メールアドレス</th>
              <th>ステータス</th>
            </tr>
          </thead>
          <tbody>
            <% @customers.each do |customer| %>
              <tr>
                <td class="align-middle"><%= customer.id %></td>
                <td  class="align-middle">
                  <%= link_to admin_customer_path(customer.id) do %><!--氏名をクリック→会員詳細画面へ遷移-->
                    <%= customer.last_name + customer.first_name %>
                  <% end %>
                </td>
                <td class="align-middle"><%= customer.email %></td>
                <td class="align-middle">
                  <% if customer.is_active == true %><!--もし会員が有効なら（trueなら）-->
                    <p class="text-success font-weight-bold">有効</p>
                  <% else %>
                    <p class="text-danger font-weight-bold">退会</p>
                  <% end %>
                </td>
              </tr>
            <% end %>
          </tbody>
        </table>
      </div>
    </div>
  </div>
  <div class='row'>
    <div class="col">
      <div style="display: flex; justify-content: center;">
        <%= paginate @customers, class: "pagination" %>
      </div>
    </div>
  </div>
</div>

app/views/admin/customers/show.html.erb
<!--顧客詳細画面　9P-->
<div class="container">
  <div class="row my-3">
    <div>
      <h3><%= @customer.last_name + @customer.first_name %>さんの会員詳細</h3>
    </div>
    <table class="table table-borderless">
      <tr>
        <td>会員ID</td>
        <td><%= @customer.id %></td>
      </tr>
      <tr>
        <td>氏名</td>
        <td><%= @customer.last_name %>　<%= @customer.first_name %></td>
      </tr>
      <tr>
        <td>フリガナ</td>
        <td><%= @customer.last_name_kana %>　<%= @customer.first_name_kana %></td>
      </tr>
      <tr>
        <td>郵便番号</td>
        <td><%= @customer.postal_code %></td>
      </tr>
      <tr>
        <td>住所</td>
        <td><%= @customer.address %></td>
      </tr>
      <tr>
        <td>電話番号</td>
        <td><%= @customer.telephone_number %></td>
      </tr>
      <tr>
        <td>メールアドレス</td>
        <td><%= @customer.email %></td>
      </tr>
      <tr>
        <td>会員ステータス</td>
        <td>
          <% if @customer.is_active == true %><!--もし会員が有効なら（trueなら）-->
            <p class="text-success font-weight-bold" style="vertical-align: middle;">有効</p>
          <% else %>
            <p class="text-danger font-weight-bold">退会</p>
          <% end %>
        </td>
      </tr>
    </table>
    <div class="row mb-2">
      <%= link_to '編集する', edit_admin_customer_path(@customer), class: "btn btn-sm btn-success"%>
      <%= link_to '注文履歴一覧を見る', admin_path, class: "btn btn-sm btn-primary"%>
   </div>
  </div>
</div>

app/views/admin/customers/update.html.erb
<h1>Admin::Customers#update</h1>
<p>Find me in app/views/admin/customers/update.html.erb</p>