config/routes.rb
Rails.application.routes.draw do

  devise_for :admin, skip: [:registrations, :passwords], controllers: {
    sessions: "admin/sessions"
  }

  devise_for :customers,skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }

  # Public側の記述
  root 'public/homes#top'
  get 'about', to: 'public/homes#about'
  scope module: :public do
    resources :cart_items, only: [:index, :update, :destroy, :create] do
      delete 'clear', on: :collection
    end
    resources :addresses, only: [:index, :edit, :create, :update, :destroy]
    post '/orders/confirm' => 'orders#confirm', as: "confirm_orders"
    get '/orders/confirm' => 'orders#confirm'
    resources :orders, only: [:new, :create, :index, :show] do
      collection do
        get 'complete'
      end
    end

    get '/customers/my_page' => 'customers#show'
    get '/customers/information/edit' => 'customers#edit'
    patch '/customers/information' => 'customers#update'
    get '/customers/check' => 'customers#check'
    get '/customers/out' => 'customers#out'

    resources :items, only: [:index, :show]
  end

  # Admin側の記述
  get 'admin', to: 'admin/homes#top'
  namespace :admin do
    resources :order_details, only: [:update]
    resources :orders, only: [:show, :update]
    resources :customers, only: [:index, :show, :edit, :update]
    resources :genres, only: [:index, :create, :edit, :update]
    resources :items, only: [:index, :new, :create, :show, :edit, :update]
  end

end

app/models/order.rb
class Order < ApplicationRecord

  VALID_POSTAL_CODE_REGEX = /\A\d{7}\z/

  validates :total_payment, presence: true
  validates :payment_type, presence: true
  validates :shipping_cost, presence: true
  validates :address, length: { in: 1..50 }
  validates :postal_code, presence: true, format: { with: VALID_POSTAL_CODE_REGEX }
  validates :name, length: { in: 1..50 }

  has_many :order_details, dependent: :destroy
  belongs_to :customer
  has_many :items, through: :order_details

  enum payment_type: {クレジットカード:0, 銀行振込:1}
  enum status: {入金待ち:0, 入金確認:1, 製作中:2, 発送準備中:3, 発送済み:4}

end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < ApplicationController
  before_action :authenticate_admin!

  def show
    @order = Order.find(params[:id])
    @orders = Order.all
  end

  def update
    @order = Order.find(params[:id])
    @order_details = @order.order_details

    if @order.update(order_params)  #注文ステータスが「入金確認」になったら、自動で全ての制作ステータスが「製作待ち」になる
      if @order.status == "入金確認"
        @order_details.update_all(making_status: OrderDetail.making_statuses[:製作待ち])
      end
      redirect_to admin_order_path(@order), notice: '更新が成功しました'
    else
      redirect_to admin_path#追加設定
    end
  end

  private

  def order_params
    params.require(:order).permit(:status)
  end

end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/views/admin/orders/show.html.erb
<!--注文詳細画面(ステータス編集を兼ねる) 13P-->
<div class="container">
  <div class="row my-3">

    <div>
      <h3>注文履歴詳細</h3>
    </div>
    <table class="table table-borderless"><!--購入者に関する情報-->
      <tr>
        <td>購入者</td>
        <td>
          <%= link_to admin_customer_path(@order.customer.id) do %><!--氏名をクリック→会員詳細画面へ遷移-->
            <%= @order.customer.last_name + @order.customer.first_name %>
          <% end %>
        </td>
      </tr>
      <tr>
        <td>注文日</td>
        <td><%= @order.created_at.strftime('%Y/%m/%d') %></td>
      </tr>
      <tr>
        <td>配送先</td>
        <td>〒<%= @order.postal_code %> <%= @order.address %><br>
            <%= @order.name %>
        </td>
      </tr>
      <tr>
        <td>支払い方法</td>
        <td><%= @order.payment_type %></td>
      </tr>
      <tr>
        <td>注文ステータス</td>
        <td>
          <%= form_with model: @order, url: admin_order_path(@order), method: :patch do |f| %>
            <%= f.select :status, Order.statuses.keys.map %>
            <%= f.submit '更新', class:"btn btn-outline-success" %><!--更新ボタン-->
          <% end %>
        </td>
      </tr>
    </table>

    <table class="table table-bordered"><!--購入した商品に関する情報-->
      <thead>
        <tr>
          <th class="table-active">商品名</th>
          <th class="table-active">単価（税込）</th>
          <th class="table-active">数量</th>
          <th class="table-active">小計</th>
          <th class="table-active">製作ステータス</th>
          <th></th>
        </tr>
      </thead>
      <% @order.order_details.each do |order_detail| %>
        <tbody>
          <tr>
            <td><%= order_detail.item.name %></td><!--OrderDetailモデルを通してItemモデルからname情報を取得-->
            <td><%= calculate_price_including_tax(order_detail.item.price) %></td><!--ヘルパーメソッドapp/helpers/application_helper.rbから呼び出し-->
            <td><%= order_detail.amount %></td>
            <td><%= calculate_subtotal_order_detail(order_detail) %></td><!--ヘルパーメソッドapp/helpers/application_helper.rbから呼び出し-->
            <%= form_with model: order_detail, url: admin_order_detail_path(order_detail), method: :patch do |f| %>
              <td>
                <%= f.select :making_status, OrderDetail.making_statuses.keys.map %>
              </td>
              <td>
                <%= f.submit '更新', class:"btn btn-outline-success" %><!--更新ボタン-->
              </td>
            <% end %>
          </tr>
        </tbody>
      <% end %>
    </table>
    <table><!--注文にかかった金額-->
      <tr>
        <th>商品合計</th>
        <td><%= calculate_total_order_detail(@order.order_details) %>円</td><!--ヘルパーメソッドapp/helpers/application_helper.rbから呼び出し-->
      </tr>
      <tr>
        <th>送料</th>
        <td><%= @order.shipping_cost %>円</td>
      </tr>
      <tr>
        <th>請求額合計</th>
        <th><%= calculate_sum_order_detail(@order) %>円</th><!--ヘルパーメソッドapp/helpers/application_helper.rbから呼び出し-->
      </tr>
    </table>

  </div>
</div>

app/views/admin/orders/update.html.erb
<h1>Admin::Orders#update</h1>
<p>Find me in app/views/admin/orders/update.html.erb</p>