config/routes.rb
Rails.application.routes.draw do

  devise_for :admin, skip: [:registrations, :passwords], controllers: {
    sessions: "admin/sessions"
  }

  devise_for :customers,skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }

  # Public側の記述
  root 'public/homes#top'
  get 'about', to: 'public/homes#about'
  scope module: :public do
    resources :cart_items, only: [:index, :update, :destroy, :create] do
      delete 'clear', on: :collection
    end
    resources :addresses, only: [:index, :edit, :create, :update, :destroy]
    post '/orders/confirm' => 'orders#confirm', as: "confirm_orders"
    get '/orders/confirm' => 'orders#confirm'
    resources :orders, only: [:new, :create, :index, :show] do
      collection do
        get 'complete'
      end
    end

    get '/customers/my_page' => 'customers#show'
    get '/customers/information/edit' => 'customers#edit'
    patch '/customers/information' => 'customers#update'
    get '/customers/check' => 'customers#check'
    get '/customers/out' => 'customers#out'

    resources :items, only: [:index, :show]
  end

  # Admin側の記述
  get 'admin', to: 'admin/homes#top'
  namespace :admin do
    resources :order_details, only: [:update]
    resources :orders, only: [:show, :update]
    resources :customers, only: [:index, :show, :edit, :update]
    resources :genres, only: [:index, :create, :edit, :update]
    resources :items, only: [:index, :new, :create, :show, :edit, :update]
  end

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ながのCAKE</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://fonts.googleapis.com/css?family=M+PLUS+1p" rel="stylesheet">
  </head>

  <body>
    <%= stylesheet_link_tag 'application' %>
    <header class="mx-auto text-center bg-dark text-white">
      <% if customer_signed_in? %>
        <div class="d-flex justify-content-between align-items-center px-5">
          <h3 class="logo wf-mplus1p"><%= link_to "ながのcake", root_path %></h3>
          <h5 class = “wf-mplus1p”>＼ようこそ、　<strong><%= current_customer.last_name %></strong>　さん！／</h5>
          <div class="header-bottom">
            <ul class="nav nav-pills justify-content-end">
              <li class = “wf-mplus1p”><%= link_to "マイページ", customers_my_page_path, class:"nav-link" %></li>
              <li class = “wf-mplus1p”><%= link_to "商品一覧", items_path, class: "nav-link" %></li>
              <li class = “wf-mplus1p”><%= link_to "カート", cart_items_path, class: "nav-link" %></li>
              <li class = “wf-mplus1p”><%= link_to "ログアウト", destroy_customer_session_path, class:"nav-link", method: :delete %></li>
            </ul>
          </div>
        </div>
      <% elsif admin_signed_in? %>
        <div class="d-flex justify-content-between align-items-center px-5">
          <h3 class="logo wf-mplus1p"><%= link_to "ながのcake", admin_path %></h3>
          <ul class="nav nav-pills justify-content-end">
            <li class = “wf-mplus1p”><%= link_to "商品一覧", admin_items_path, class:"nav-link" %></li>
            <li class = “wf-mplus1p”><%= link_to "会員一覧", admin_customers_path, class:"nav-link" %></li>
            <li class = “wf-mplus1p”><%= link_to "注文履歴一覧", admin_path, class:"nav-link" %></li>
            <li class = “wf-mplus1p”><%= link_to "ジャンル一覧", admin_genres_path, class:"nav-link"  %></li>
            <li class = “wf-mplus1p”><%= link_to "ログアウト", destroy_admin_session_path, method: :delete, class:"nav-link" %></li>
          </ul>
        </div>
      <% else %>
        <div class="d-flex justify-content-between align-items-center px-5">
          <h3 class="logo wf-mplus1p"><%= link_to "ながのcake", root_path %></h3>
          <ul class="nav nav-pills justify-content-end">
            <li class = “wf-mplus1p”><%= link_to "About", about_path, class:"nav-link" %></li>
            <li class = “wf-mplus1p”><%= link_to "商品一覧", items_path, class: "nav-link" %></li>
            <li class = “wf-mplus1p”><%= link_to "新規登録", new_customer_registration_path, class: "nav-link" %></li>
            <li class = “wf-mplus1p”><%= link_to "ログイン", new_customer_session_path, class:"nav-link" %></li>
          </ul>
        </div>
      <% end %>
    </header>
    <main class="mt-5">
      <% flash.each do |message_type, message| %>
        <div class="flash-message <%= message_type %>"><%= message %></div>
      <% end %>
    </main>
    <!--↑追加しました（byみっころ）-->
    <%= yield %>
    <footer>
      <div class="container">
        <div class="text-center text-muted" style="margin: 50px 0;">© 2024  もみましぷりん</div>
      </div>
    </footer>
  </body>
</html>